// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL53YFY34Nzasf7mxAHFEXfFlWUouuwy0',
    appId: '1:948210243667:web:9ffc1b5a6424cf7eac0ea6',
    messagingSenderId: '948210243667',
    projectId: 'fitness-app-18ba0',
    authDomain: 'fitness-app-18ba0.firebaseapp.com',
    storageBucket: 'fitness-app-18ba0.firebasestorage.app',
    measurementId: 'G-294YLSFE1P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4XXH2TAB9EHVakO-vnDbIS0xbiTi4tl4',
    appId: '1:948210243667:android:41d00feb9c4651c7ac0ea6',
    messagingSenderId: '948210243667',
    projectId: 'fitness-app-18ba0',
    storageBucket: 'fitness-app-18ba0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoGJmq4oG0VgWDaf1rK9jcUtZqMWat56g',
    appId: '1:948210243667:ios:b1d155888ec1cc68ac0ea6',
    messagingSenderId: '948210243667',
    projectId: 'fitness-app-18ba0',
    storageBucket: 'fitness-app-18ba0.firebasestorage.app',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoGJmq4oG0VgWDaf1rK9jcUtZqMWat56g',
    appId: '1:948210243667:ios:b1d155888ec1cc68ac0ea6',
    messagingSenderId: '948210243667',
    projectId: 'fitness-app-18ba0',
    storageBucket: 'fitness-app-18ba0.firebasestorage.app',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBL53YFY34Nzasf7mxAHFEXfFlWUouuwy0',
    appId: '1:948210243667:web:bfe42a5026a63c98ac0ea6',
    messagingSenderId: '948210243667',
    projectId: 'fitness-app-18ba0',
    authDomain: 'fitness-app-18ba0.firebaseapp.com',
    storageBucket: 'fitness-app-18ba0.firebasestorage.app',
    measurementId: 'G-LDTVNMR5HT',
  );
}
